#include "Fonts.h"

#include "Fonts/FreeMonoBold9pt7b.h"
#include "Fonts/FreeMonoBold12pt7b.h"
#include "Fonts/FreeSansBold9pt7b.h"
#include "Fonts/FreeSansBold12pt7b.h"
#include "Fonts/FreeSansBold18pt7b.h"
#include "Fonts/FreeSansBold30pt7b.h"
#include "Fonts/FreeSansBold75pt7b.h"
#include "Fonts/SansSerif_bold_84_nr.h"
